### ISSUE TITLE
Port to esp8266/esp32

### ISSUE THREAD

**Issue by akira-kun** [zaps166/libsimplewebm#3]
Have any one trying to port (audio only) to esp8266 or esp32?

**Comment by zaps166** [comment]
I don't know. If you have C and C++ compiler for this device, you can try to compile `libvorbis` and `libopus`, next compile this project and link to them (you can disable/remove video part) and give us your results!

A few years ago I was able to compile `libvorbis` for ARM bare-metal, so it should be possible.

You might need to do minor code changes to compile. Of course don't use Qt `*.pro` file.

If your MCU doesn't support floating point numbers, you can use `libtremor` which is `libvorbis` integer-only implementation.
